version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gbawo-finance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-gbawo_finance}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - gbawo-finance-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-gbawo_finance}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer:4.8.1
    container_name: gbawo-finance-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - gbawo-finance-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula

volumes:
  postgres_data:
    driver: local

networks:
  gbawo-finance-network:
    driver: bridge 