/**
 * Constants for magic numbers and configuration values
 */

export const TIME_CONSTANTS = {
  WEBHOOK_TIMEOUT_DEFAULT: 30,
  WEBHOOK_TIMEOUT_EXTENDED: 60,
  RATE_LIMIT_DEFAULT: 1000,
  RATE_LIMIT_EXTENDED: 2000,
  CRYPTO_CONFIRMATIONS_BTC: 6,
  CRYPTO_CONFIRMATIONS_ETH: 12,
  TIMEOUT_MINUTES_DEFAULT: 30,
  PROCESSING_TIME_SECONDS_DEFAULT: 180,
} as const;

export const LIMIT_CONSTANTS = {
  // KYC Level 0 (Unverified)
  KYC_LEVEL_0_DAILY: 500,
  KYC_LEVEL_0_MONTHLY: 5000,
  KYC_LEVEL_0_SINGLE: 100,

  // KYC Level 1 (Basic verification)
  KYC_LEVEL_1_DAILY: 5000,
  KYC_LEVEL_1_MONTHLY: 50000,
  KYC_LEVEL_1_SINGLE: 5000,

  // KYC Level 2 (Enhanced verification)
  KYC_LEVEL_2_DAILY: 50000,
  KYC_LEVEL_2_MONTHLY: 500000,
  KYC_LEVEL_2_SINGLE: 50000,

  // KYC Level 3 (Premium verification)
  KYC_LEVEL_3_DAILY: 500000,
  KYC_LEVEL_3_MONTHLY: 5000000,
  KYC_LEVEL_3_SINGLE: 500000,
} as const;

export const FEE_CONSTANTS = {
  PLATFORM_FEE_DEFAULT: 2.5,
  NETWORK_FEE_BTC_DEFAULT: 0.00001,
  NETWORK_FEE_ETH_DEFAULT: 0.002,
  BANK_TRANSFER_FEE_DEFAULT: 15.0,
  CORRESPONDENT_BANK_FEE_DEFAULT: 25.0,
  INTEGRATOR_FEE_DEFAULT: 1.0,
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const PAGINATION_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
