/**
 * Security-related enums for the Gbawo Finance Core Service
 */

export enum SecurityEventSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

export enum UserAccountStatus {
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
  PENDING = 'pending',
  INACTIVE = 'inactive',
}

export enum ErrorType {
  VALIDATION_ERROR = 'validation_error',
  INSUFFICIENT_KYC_LEVEL = 'insufficient_kyc_level',
  KYC_VERIFICATION_REQUIRED = 'kyc_verification_required',
  INVALID_ACCOUNT = 'INVALID_ACCOUNT',
  AUTHENTICATION_FAILURE = 'authentication_failure',
  AUTHORIZATION_FAILURE = 'authorization_failure',
}

export enum SecurityEventType {
  // Critical Events
  MALICIOUS_INPUT_DETECTED = 'MALICIOUS_INPUT_DETECTED',
  PROTOTYPE_POLLUTION_ATTEMPT = 'PROTOTYPE_POLLUTION_ATTEMPT',
  SQL_INJECTION_ATTEMPT = 'SQL_INJECTION_ATTEMPT',
  POTENTIAL_SQL_INJECTION = 'POTENTIAL_SQL_INJECTION',
  SERVICE_STARTED = 'SERVICE_STARTED',

  // High Priority Events
  SECURITY_THREAT_DETECTED = 'SECURITY_THREAT_DETECTED',
  SUSPICIOUS_PATH_ACCESS = 'SUSPICIOUS_PATH_ACCESS',
  HEADER_VALIDATION_FAILED = 'HEADER_VALIDATION_FAILED',
  PATH_TRAVERSAL_ATTEMPT = 'PATH_TRAVERSAL_ATTEMPT',
  POTENTIAL_XSS_ATTEMPT = 'POTENTIAL_XSS_ATTEMPT',

  // Medium Priority Events
  CORS_VIOLATION = 'CORS_VIOLATION',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  OVERSIZED_REQUEST = 'OVERSIZED_REQUEST',
  EXTERNAL_IP_ACCESS = 'EXTERNAL_IP_ACCESS',
  REQUEST_FAILED = 'REQUEST_FAILED',
  AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE',

  // Low Priority Events
  REQUEST_RECEIVED = 'REQUEST_RECEIVED',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED',
}
